export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'
export const CHANGE_SEARCH_PENDING = 'CHANGE_SEARCH_PENDING'
export const CHANGE_SEARCH_SUCCESS = 'CHANGE_SEARCH_SUCCESS'
export const CHANGE_SEARCH_FAIL = 'CHANGE_SEARCH_FAIL'